name = "new-navigator"
compatibility_date = "2026-08-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "navigator-db"
database_id = "91ed5d9a-6fa6-405a-a6e1-3e54ea11414d"
