import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import source from '../src/Data/source.js'
import { hashPassword } from '../functions/lib/auth.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function parseArgs(argv) {
  const args = {}
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) args[argv[i].slice(2)] = argv[i + 1]
  }
  return args
}

function sqlQuote(str) {
  return `'${String(str).replace(/'/g, "''")}'`
}

const args = parseArgs(process.argv.slice(2))
const username = args.user || 'blake'
const password = args.password || process.env.SEED_PASSWORD
if (!password) {
  console.error('Usage: node scripts/import-source.mjs --out migrations/0002_seed.sql --user blake --password <your-password>')
  console.error('Or set SEED_PASSWORD env var.')
  process.exit(1)
}

const { hash, salt } = await hashPassword(password)

const lines = []
lines.push('-- generated by scripts/import-source.mjs, do not edit by hand')
lines.push(`DELETE FROM bookmarks WHERE user_id = (SELECT id FROM users WHERE username = ${sqlQuote(username)});`)
lines.push(`DELETE FROM users WHERE username = ${sqlQuote(username)};`)
lines.push(
  `INSERT INTO users (username, password_hash, salt) VALUES (${sqlQuote(username)}, ${sqlQuote(hash)}, ${sqlQuote(salt)});`
)

for (const category of Object.keys(source).filter((k) => k !== 'user')) {
  const items = source[category] || []
  for (let i = 0; i < items.length; i++) {
    const sort = items.length - i
    lines.push(
      `INSERT INTO bookmarks (user_id, category, href, value, sort) VALUES (` +
        `(SELECT id FROM users WHERE username = ${sqlQuote(username)}), ` +
        `${sqlQuote(category)}, ${sqlQuote(items[i].href)}, ${sqlQuote(items[i].value)}, ${sort});`
    )
  }
}

const sql = lines.join('\n') + '\n'

const out = args.out
if (out) {
  const outPath = path.resolve(__dirname, '..', out)
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, sql, 'utf8')
  console.log(`seed written to ${outPath}`)
} else {
  process.stdout.write(sql)
}
console.log(`account "${username}" ready, ${Object.keys(source).length - 1} categories exported`)
